name = "MLJFair"
uuid = "7c232609-d7a1-4356-98a6-13e736dd6dcd"
authors = ["ashryaagr <ashryaagr@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
